from Player.QPlayer import QPlayer
from Player.ClassicPlayer import ClassicPlayer
from Player.DeepQPlayer import DeepQPlayer
from Player.HumanPlayer import HumanPlayer
from Player.HumanQPlayer import HumanQPlayer
from Player.RandomClassicPlayer import RandomClassicPlayer
from Player.RandomQPlayer import RandomQPlayer
from Player.RandomSPPlayer import RandomSPPlayer
from Player.SPPlayer import SPPlayer